version: "3.7"

services:
  load:
    build:
      context: ./load_file_service
      dockerfile: Dockerfile
    volumes:
      - "./load_file_service:/code"
    restart: on-failure
    env_file: ./.env
    ports:
      - "90:8000"

  process:
    build:
      context: ./process_file_service
      dockerfile: Dockerfile
    volumes:
      - "./process_file_service:/code"
    restart: on-failure
    env_file: ./.env
    ports:
      - "91:8001"
