version: "3.7"

services:
  db:
    image: postgres
    restart: on-failure
    env_file: ./.env
    volumes:
      - "./.compose/pgdata:/var/lib/postgresql/data"
    ports:
      - "5433:5432"

  load_file_service:
    build:
      context: ./load_file_service
      dockerfile: Dockerfile
    volumes:
      - "./load_file_service:/code"
    restart: on-failure
    env_file: ./.env
    depends_on:
      - db

  process_file_service:
    build:
      context: ./process_file_service
      dockerfile: Dockerfile
    volumes:
      - "./process_file_service:/code"
    restart: on-failure
    env_file: ./.env
    depends_on:
      - db
